IV Objetivo 3 [IV-21-22]
eantoniocalo18/IV pull request #26
Opened 2021-12-05 14:07 UTC by eantoniocalo18

Se ha trabajado en la elección de un gestor de tareas y uno de dependencias,
solucionando así los siguientes issues:
- closes #24
- closes #25
Además, se ha actualizado el README.md para incluir la información relativa a los mismos.

2021-12-07 18:37 UTC, eantoniocalo18 commented
@JJ Listo para revisión.

2021-12-09 09:05 UTC, eantoniocalo18 commented
@JJ Listo para revisión.

2021-12-09 19:16 UTC, JJ requested changes
Consulta los comentarios ,la lista de comprobación y los errores frecuentes para superar el objetivo. Ánimo.

2021-12-09 19:16 UTC, JJ commented on README.md
> +En el caso de sistemas Unix se podrá utilizar el siguiente comando
Si vais a copiar las instrucciones que hay en poetry, no lo hagáis. No aporta nada ni a vuestra evaluación ni al que lea el README. Tampoco evidencia que entiendas lo que hace esa orden (y vas a necesitar entenderlo para el objetivo 5)

2021-12-09 19:16 UTC, JJ commented on README.md
> +  - poetry shell --> Abrirá una terminal para poder ejecutar las diferentes tareas del proyecto
Si invoke no funciona desde fuera de poetry, entonces no lo puedes usar como gestor de tareas.

2021-12-09 19:16 UTC, JJ commented on docs/eleccion_gestores.md
> +Invoke es una herramienta y biblioteca de ejecución de tareas de Python. Es similar a Rake en Ruby. Sigue en desarrollo y la última versión fue lanzada en Julio 2021.
No me comuniques la decisión. Ya lo hemos dicho hoy en clase y está en los errores frecuentes. Repetidamente.

2021-12-10 09:39 UTC, eantoniocalo18 commented
@JJ Listo para revisión.

2021-12-10 10:23 UTC, JJ requested changes
Mira los errores frecuentes, y también la lista de comprobación.

2021-12-10 10:23 UTC, JJ commented on docs/eleccion_gestores.md
> +# Gestor de dependencias
¿Quién ha dicho que hay que seleccionar un gestor de dependencias?

2021-12-10 10:23 UTC, JJ commented on docs/eleccion_gestores.md
> +- Sintaxis sencilla
Ninguno de ellos tiene que ver con el proyecto.

2021-12-10 10:23 UTC, JJ commented on docs/eleccion_gestores.md
> +
¿Te das cuenta que estás hablando de gestores de dependencias en vez de *task runners*?

2021-12-10 10:23 UTC, JJ commented on docs/eleccion_lenguaje.md
> + - Facilidad de sintáxis y comodidad para desarrollo.
typo

2021-12-10 10:23 UTC, JJ commented on tasks.py
> +	run("python src/producto.py")
Esto no comprueba la sintaxis, sino que lo ejecuta. Si hay algún fallo en la ejecución, también fallará.

2021-12-10 16:13 UTC, eantoniocalo18 commented
Se ha actualizado la documentación y corregido los errores.
@JJ Listo para revisión.

2021-12-10 16:34 UTC, JJ requested changes
OK, te vas acercando...

2021-12-10 16:34 UTC, JJ commented on docs/eleccion_gestores.md
> +- Sintaxis sencilla
Ahora son los mismos requisitos, pero para una cosa diferente...

2021-12-10 16:34 UTC, JJ commented on docs/eleccion_gestores.md
> +Lo principal para un desarrollador es que el software que utilice le facilite todo, es por ello que un requisito con mucho valor que su uso sea fácil, sin tener que configurar en exceso y con un uso
¿Eso es lo principal?

2021-12-10 16:34 UTC, JJ commented on pyproject.toml
> +python = "2.7.18"
¿Sólo esa versión?

2021-12-10 16:34 UTC, JJ commented on pyproject.toml
> +invoke = "^1.3.0"
¿Sabes la diferencia entre dependencias de desarrollo y de producción?

2021-12-10 16:34 UTC, JJ commented on docs/eleccion_gestores.md
> +- make: Permite configurar en un solo archivo Makefile todas las acciones, aunque no es un task runner como tal se puede usar
Podías siquiera intentar poner cómo cumplen o no los criterios los que pones.

2021-12-10 16:34 UTC, JJ commented on docs/eleccion_gestores.md
> +
And the winner is... Porque...

2021-12-10 18:31 UTC, eantoniocalo18 commented
Se ha actualizado la documentación y corregido los errores.
@JJ Listo para revisión.

2021-12-11 08:54 UTC, JJ approved these changes
Te lo voy a dejar pasar, porque ya mucho más no va a mejorar. Tendrás que justificar bien las elecciones en los siguientes objetivos.

2021-12-11 08:54 UTC, JJ commented on docs/eleccion_gestores.md
> +- make: Permite configurar en un solo archivo Makefile todas las acciones, aunque no es un task runner como tal se puede usar
Sigues sin ponerlo.

2021-12-11 08:54 UTC, JJ commented on docs/eleccion_gestores.md
> +  - Es el más popular para proyectos Python.
¿Prueba?

2021-12-11 08:54 UTC, JJ commented on docs/eleccion_gestores.md
> +  - Las desventajas es que no es un task runner como tal por lo que su popularidad como task runner no es mucha. Además, su uso no es específico de Python pues es un comando de Linux.
No sólo lo es, sino que es el task runner por antonomasia.

2021-12-11 16:49 UTC, merged