[IV-21-22] Objetivo 4
eantoniocalo18/IV pull request #32
Opened 2021-12-14 17:44 UTC by eantoniocalo18

Entrega del objetivo 4, en el que se han llevado a cabo las siguientes acciones:
- Elección de un marco de test y una librería de aserciones, junto con la justificación de elección.
- Implementación de métodos en las clases Inventario y Producto que han sido necesarios para implementar los test.
- Creación de un archivo funciones_test.py en el que se han incluido funciones necesarias para la simulación de los test.
- Justificación y explicación del [Milestone 1] (https://github.com/eantoniocalo18/IV/milestone/3) donde se ha justificado el PMV y los test necesarios para cumplirlo, dando prioridad a las clases que intervienen en estos test.
- Se han asignado a M1 las HUs relacionadas con los test implementados.
- Se han creado 3 test, incluidos en [/test] (https://github.com/eantoniocalo18/IV/test) que comprueban que el código realizará lo que el usuario espera.
- Se han añadido comentarios a #10 , #13 y #15 indicando los criterios de aceptación que tienen que cumplir los test.
- Se ha actualizado el fichero iv.yaml incluyendo la nueva clave 'test' 
- Se ha actualizado la información del README incluyendo la explicación de los test y su manual de ejecución.

Cabe destacar, que el diseño de los test ha sido a priori, teniendo en cuenta las HUs y siguiendo los principios F.I.R.S.T

Adjunto la lista de comprobación del Objetivo 4:
* [✓]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [✓]  ¿Se ha intentado cubrir una parte de la lógica de negocio que se
   esté desarrollando?
* [✓]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [✓]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ✓]  ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ✓] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ✓]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ✓]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?

2021-12-14 17:55 UTC, eantoniocalo18 commented
@JJ Listo para revisión.

2021-12-15 09:35 UTC, Olasergiolas requested changes
Las justificaciones de la documentación me parecen completas y correctas 🥇. Échale un vistazo a lo que te he comentado de los tests.

2021-12-15 09:35 UTC, Olasergiolas commented on test/test_estado_almacen.py
> +    assert_that(inventario.get_espacio_usado()).is_less_than(inventario.get_dimensiones())
Podrías añadir una descripción a las aserciones en los [assert_that](https://assertpy.github.io/docs.html#assertpy.assertpy.assert_that) para dar algo de contexto sobre qué está fallando.

2021-12-15 09:35 UTC, Olasergiolas commented on test/test_poco_stock.py
> +from src.inventario import Inventario
Creo que no merece la pena dedicar un fichero nuevo a cada test y aún menos teniendo en cuenta que se te repiten los imports en todos ellos.

2021-12-15 10:56 UTC, eantoniocalo18 commented on test/test_poco_stock.py
> +from src.inventario import Inventario
Sí, tienes razón, además todos los test son de la misma clase.

2021-12-15 10:56 UTC, eantoniocalo18 commented on test/test_estado_almacen.py
> +    assert_that(inventario.get_espacio_usado()).is_less_than(inventario.get_dimensiones())
Buena idea! 👍

2021-12-15 11:26 UTC, Pablont98 commented
He revisado tanto la documentación, como el código y los diferentes archivos del proyecto. En general está muy correcto y bastante completo. Y con los últimos cambios propuestos por el compañero, veo que este objetivo está listo para pasar. 
La única pega es que en el archivo pyproject.toml pones que la versión de python es la 2.7.18 pero en la documentación sobre elección de lenguaje dices que utilizas la 3.8.
Por último corrige los enlaces del README a esta documentación, cuando intento acceder desde el README a la documentación me lleva a una página con mensaje "not found".

2021-12-15 16:09 UTC, Balrrach requested changes

2021-12-15 16:10 UTC, Balrrach commented
Lo verdaderamente importante es el comentario acerca de la logica de negocio. El resto son good to have pero realmente no forman parte del objetivo.

2021-12-15 16:45 UTC, eantoniocalo18 commented on src/inventario.py
> +        self.productos_dict = productos_dict
De acuerdo, tienes razón. Buen apunte 👍

2021-12-15 16:45 UTC, eantoniocalo18 commented on test/test_estado_almacen.py
> +    assert_that(productos, description='Se han cargado mal los productos').is_not_empty()
Vale, me parece buena idea. 👍

2021-12-15 16:53 UTC, eantoniocalo18 commented on test/test_inventario.py
> +
El testeo en este objetivo es sobre el inicio de la lógica de negocio, en el que se incluye el testeo de las funciones principales que darán pie al resto de la implementación. 
Todo el proceso, así como el issue que planteas que podría servirme para resolver una historia de usuario está representado en #10 y la información relativa al inicio de la implementación de la lógica de negocio está en [M1](https://github.com/eantoniocalo18/IV/milestone/3).
Aun así, el comentario me ha servido para darme cuenta de los errores que probablemente iba a cometer en siguientes objetivos, así que perfecto :)
PD: Gracias por el análisis tan completo del proyecto 👍

2021-12-15 17:14 UTC, eantoniocalo18 commented
Tras analizar y valorar los comentarios de @Pablont98 @Olasergiolas y @Balrrach se han realizado una serie de modificaciones con los que creo que el objetivo está listo para su revisión.
@JJ Listo para revisión.

2021-12-15 17:17 UTC, eantoniocalo18 commented on src/inventario.py
> +        return espacio_ocupado
Es un diccionario cuya primera posición almacena un objeto de tipo Producto y su cantidad.
No se han declarado los mismos atributos para que todo el peso del diseño recaiga exclusivamente en una clase Inventario. De todas formas, creo que lo lioso era el nombre de la variable que, como me has dejado escrito en otro comentario es liosa y he decidido cambiarla por 'Almacen', que representa mucho mejor lo que se trata de conseguir con este atributo.

2021-12-16 08:38 UTC, eantoniocalo18 commented
> He revisado tanto la documentación, como el código y los diferentes archivos del proyecto. En general está muy correcto y bastante completo. Y con los últimos cambios propuestos por el compañero, veo que este objetivo está listo para pasar. La única pega es que en el archivo pyproject.toml pones que la versión de python es la 2.7.18 pero en la documentación sobre elección de lenguaje dices que utilizas la 3.8. Por último corrige los enlaces del README a esta documentación, cuando intento acceder desde el README a la documentación me lleva a una página con mensaje "not found".

Se ha corregido la versión errónea que había en la documentación. 
Por otra parte, los enlaces no se han corregido aún puesto que @morevi ha hecho un [PR](https://github.com/eantoniocalo18/IV/pull/33) para ello que será mergeado cuando se pase el objetivo.
Gracias! 👍

2021-12-16 11:58 UTC, JJ requested changes
La verdad que, aparte de lo poco que he dicho, nada más que añadir a lo que ha dicho @Balrrach

2021-12-16 11:58 UTC, JJ commented on docs/test.md
> +- Actualmente cuenta con más de 1,5k PRs abiertos, muchos de ellos reportando bugs sin resolver X
WTF

2021-12-16 11:58 UTC, JJ commented on docs/test.md
> +- Ofrece una sintaxis sencilla
Hombre, estaría bien que pusiérais un enlace a lo que estáis hablando...

2021-12-16 11:58 UTC, JJ commented on src/inventario.py
> +        return espacio_ocupado
Recuerda una de los principios del código limpio, que es usar las estructuras de datos para su función original. Una lista es para almecenar cosas iguales e iterar sobre ella, no para almacenar no sé qué que yo sé solo en la posición 0 y no sé qué otra cosa en la 1. Usa una tupla, que viene a ser un objeto ligero, o si hay alguna lógica de negocio o de validación, un objeto para lo mismo que lo dejará un poco más claro.

2021-12-16 19:41 UTC, JJ approved these changes
Algunos antipatrones en el código, pero objetivo superado. Te agradeceré que lo arregles antes dle siguiente objetivo.

2021-12-16 19:41 UTC, JJ commented on docs/test.md
> +- Ofrece una sintaxis sencilla
... y corrigiérais el typo

2021-12-16 19:41 UTC, JJ commented on test/funciones_test.py
> +            diccionario[productos[i]]= rows[6]
Igual, estás extrayendo un elemento rándom sin justificación. Puedes convertir cada fila del CSV a un objeto o tupla y estará un poco más claro qué haces.

2021-12-16 19:41 UTC, JJ commented on test/funciones_test.py
> +            diccionario[productos[i]]= rows[6]
Estás usando una variable que no sirve para nada en vez de usar `append` (o push, no recuerdo qué es lo que tiene Python). Es más, puedes usar un map directamente (creo que funciona sobre iteradores, si no, una list comprehension)

2021-12-16 19:41 UTC, JJ commented on test/funciones_test.py
> +            producto = Producto(id,nombre,precio,espacio,cantidad_baja, cantidad_alta)
Variables innecesarias. Pasa la lista a Producto.

2021-12-17 08:32 UTC, merged