[IV-21-22] Objetivo 5
eantoniocalo18/IV pull request #36
Opened 2021-12-17 09:49 UTC by eantoniocalo18

Entrega del objetivo 4, en el que se han llevado a cabo las siguientes acciones:
- Se añade Dockerfile para construcción de contenedor Docker, solucionando el issue representado en #34.
- Se añade un Github Action para la construcción automática del contenedor en Dockerhub, solucionando el issue representado en #35.
- Se crea un archivo [Dockers](https://github.com/eantoniocalo18/IV/blob/Objetivo-5/docs/dockers.md) donde se muestra la información referente a la elección de la imagen base.
- Se añaden dos nuevas funciones para el gestor de tareas con el fin de poder crear una imagen docker y poder ejecutarla

* [✓ ]  ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen?
* [✓ ]  ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests?
* [✓ ]  ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ✓]  ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [✓ ]  ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?

2021-12-20 16:33 UTC, JJ commented
⛹ Revisores → @gomares @lentes4k @joaquingv12

2021-12-20 17:18 UTC, lentes4k reviewed
En general muy buen curro.
Me llaman la atención varias cosas.
1º. La elección de python3.9 en lugar de la 3.10 que es la más actual. Podrías documentar dicha elección.
2º Comentas que has elegido slim por algunas razones pero se me quedan cortas. En el caso de la búsqueda de imágenes pequeñas `alpine` puede ser mejor opción
3º No documentas por qué, habiendo elegido la versión `slim` te has quedado con `bullseye`
Tengo entendido que `slim` corre sobre `debian` y este segundo nombre del contenedor es el que se refiere a la versión de `debian` has cogido esa por algo en especial?
Por lo demás felicitarte de nuevo por el trabajo, sobre todo por el fantastico uso de las GH Actions 😎

2021-12-20 17:42 UTC, joaquingv12 reviewed
Aparte de lo comentado por el compañero, he encontrado un error frecuente del Dockerfile.

2021-12-20 17:42 UTC, joaquingv12 commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py ./
El `WORKDIR /app/test` no debería estar antes de copiar los archivos ya que cuando montes tu repositorio en esa carpeta con ```docker run -t -v `pwd`:/app/test eantoniocalo/iv``` estos archivos se sobrescribirán.

2021-12-20 18:47 UTC, gomares requested changes

2021-12-20 18:47 UTC, gomares commented on Dockerfile
>  RUN useradd --create-home testuser && chown testuser:testuser /app/test
Buenas! Si como imagen eliges Alpine tienes un problemilla ya que useradd no está (anda presente en imágenes más completas como Slim o la original de Python). Es muy probable que tengas que cambiar esa línea por algo del siguiente formato:

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

2021-12-20 18:47 UTC, gomares commented on .github/workflows/actualizar_docker.yml
> +      - Objetivo-5
Aquí usaría 'Objetivo-*' para que fuera más genérico y se actualizase con los pushes de las ramas de la asignatura y no solo con la del objetivo actual, pero lo que tu prefieras.

2021-12-20 18:47 UTC, gomares commented on .github/workflows/actualizar_docker.yml
> +          password: ${{ secrets.DOCKER_PASSWORD }}
Puedes en vez de usar el password usar secrets.DOCKER_HUB_ACCESS_TOKEN  ya que es una muy buena práctica y más seguro que el password simple que solemos usar para más cuentas nuestras. Mira este enlace si te animas que es muy sencillo: https://docs.docker.com/docker-hub/access-tokens/

2021-12-20 18:57 UTC, eantoniocalo18 commented on .github/workflows/actualizar_docker.yml
> +      - Objetivo-5
Cierto! 
De todas formas tenía pensado eliminar 'branches', para que se ejecute siempre

2021-12-20 19:37 UTC, eantoniocalo18 commented on Dockerfile
> +COPY pyproject.toml poetry.lock tasks.py ./
👍

2021-12-20 19:58 UTC, eantoniocalo18 commented
> En general muy buen curro. Me llaman la atención varias cosas. 1º. La elección de python3.9 en lugar de la 3.10 que es la más actual. Podrías documentar dicha elección. 2º Comentas que has elegido slim por algunas razones pero se me quedan cortas. En el caso de la búsqueda de imágenes pequeñas `alpine` puede ser mejor opción 3º No documentas por qué, habiendo elegido la versión `slim` te has quedado con `bullseye` Tengo entendido que `slim` corre sobre `debian` y este segundo nombre del contenedor es el que se refiere a la versión de `debian` has cogido esa por algo en especial? Por lo demás felicitarte de nuevo por el trabajo, sobre todo por el fantastico uso de las GH Actions 😎

Alpine lo contemplé también pero he leído en algunas páginas web que no era buena idea porque necesitaba muchas dependencias y al final acababa ocupando bastante más que la que he usado yo.
Los demás tips los he incluido en la documentación 👍

2021-12-20 19:59 UTC, eantoniocalo18 commented
Cambios realizados en base a los comentarios de los compañeros.
@JJ Listo para revisión.

2021-12-21 12:29 UTC, JJ commented on .github/workflows/actualizar_docker.yml
> +      - Objetivo-5
Si las ramas que vas a tener son Objetivo-* y `main`, ¿para qué quieres especificar las ramas?

2021-12-21 12:30 UTC, JJ commented on Dockerfile
>  RUN useradd --create-home testuser && chown testuser:testuser /app/test
?? [Está `adduser`](https://github.com/JJ/docker-raku/blob/main/Dockerfile), que da igual que da lo mismo.

2021-12-21 12:35 UTC, JJ requested changes
Aparte de lo indicado, el milestone no refleja este dentro del PMV descrito (que tampoco se describe demasiado bien)

2021-12-21 12:35 UTC, JJ commented on Dockerfile
> +RUN  pip install poetry && poetry config virtualenvs.create false && poetry install
¿Con qué usuario estás ejecutando esto? ¿Eso corresponde a las buenas prácticas?

2021-12-21 12:35 UTC, JJ commented on docs/dockers.md
> +| s2i-base:rhel8.5  | 502 MB |   X s  |
???

2021-12-21 12:35 UTC, JJ commented on docs/dockers.md
> +*No se han ejecutado los test con RHEL8 puesto que la diferencia de tamaño ya me hace descartala
Sólo son 80 megas más

2021-12-21 12:35 UTC, JJ commented on test/funciones_test.py
> +        #el diccionario tiene como clave un objeto de tipo Producto y de valor una cantidad
No se deben usar comentarios inline.

2021-12-21 18:11 UTC, eantoniocalo18 commented
Cambios realizados. @JJ Listo para revisión.

2021-12-23 13:08 UTC, JJ requested changes
No has resuelto el problema principal.

2021-12-23 13:08 UTC, JJ commented on Dockerfile
> +RUN  pip install poetry && poetry config virtualenvs.create false && poetry install
No has contestado a esto. Y sigue sin seguir las buenas prácticas.

2021-12-24 10:37 UTC, eantoniocalo18 commented
He realizado los cambios en el Dockerfile para seguir las buenas prácticas siguiendo los siguientes enlaces:
- https://blog.arima.eu/es/2020/04/21/buenas-practicas-para-escribir-un-dockerfile.html
- https://geekflare.com/es/container-best-practices/
- https://serrodcal.medium.com/buenas-pr%C3%A1cticas-construyendo-im%C3%A1genes-docker-8a4f14f7ad1d

@joaquingv12 @lentes4k @gomares ¿podríais echarle un vistazo antes de que lo vuelva a entregar?

2021-12-28 09:52 UTC, lentes4k approved these changes
Creo que se ha resuelto lo comentado por @JJ así que por mi parte a por los siguientes hitos :sunglasses: :+1:

2021-12-28 10:41 UTC, gomares approved these changes
Creo que lo comentado por mi parte también está resuelto, buen trabajo.

2021-12-28 11:48 UTC, joaquingv12 commented on Dockerfile
> +RUN  pip install poetry && poetry config virtualenvs.create false && poetry install
Creo que deberías de crear el usuario antes de empezar a copiar los archivos e instalar las dependencias con poetry.

2021-12-28 12:04 UTC, joaquingv12 approved these changes

2021-12-28 12:05 UTC, eantoniocalo18 commented
Cambios realizados, se han corregido los errores.
@JJ Listo para revisión.

2021-12-29 17:34 UTC, JJ approved these changes
El objetivo ha pasado, pero que no vea yo un sudo.

2021-12-29 17:34 UTC, JJ commented on tasks.py
> +    run ('sudo docker run -t -v `pwd`:/app/test eantoniocalo/iv')
¿Qué os dije sobre ejecutar sudo en cualquier circunstancia, muy especialmente con Docker?

2022-01-01 20:58 UTC, merged